
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed contenedor;
	private global::Gtk.Label Lnumero1;
	private global::Gtk.Label lnumero2;
	private global::Gtk.Button bsuma;
	private global::Gtk.Button bresta;
	private global::Gtk.Button bdivision;
	private global::Gtk.Button bmultiplicar;
	private global::Gtk.Entry EntradaNumero1;
	private global::Gtk.Entry EntradaNumero2;
	private global::Gtk.Entry Resultado;
	private global::Gtk.Label lresultado;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.contenedor = new global::Gtk.Fixed ();
		this.contenedor.Name = "contenedor";
		this.contenedor.HasWindow = false;
		// Container child contenedor.Gtk.Fixed+FixedChild
		this.Lnumero1 = new global::Gtk.Label ();
		this.Lnumero1.Name = "Lnumero1";
		this.Lnumero1.LabelProp = global::Mono.Unix.Catalog.GetString ("numero 1");
		this.contenedor.Add (this.Lnumero1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.contenedor [this.Lnumero1]));
		w1.X = 67;
		w1.Y = 45;
		// Container child contenedor.Gtk.Fixed+FixedChild
		this.lnumero2 = new global::Gtk.Label ();
		this.lnumero2.Name = "lnumero2";
		this.lnumero2.LabelProp = global::Mono.Unix.Catalog.GetString ("numero2");
		this.contenedor.Add (this.lnumero2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.contenedor [this.lnumero2]));
		w2.X = 215;
		w2.Y = 44;
		// Container child contenedor.Gtk.Fixed+FixedChild
		this.bsuma = new global::Gtk.Button ();
		this.bsuma.CanFocus = true;
		this.bsuma.Name = "bsuma";
		this.bsuma.UseUnderline = true;
		this.bsuma.Label = global::Mono.Unix.Catalog.GetString ("SUMA");
		this.contenedor.Add (this.bsuma);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.contenedor [this.bsuma]));
		w3.X = 27;
		w3.Y = 186;
		// Container child contenedor.Gtk.Fixed+FixedChild
		this.bresta = new global::Gtk.Button ();
		this.bresta.CanFocus = true;
		this.bresta.Name = "bresta";
		this.bresta.UseUnderline = true;
		this.bresta.Label = global::Mono.Unix.Catalog.GetString ("RESTA");
		this.contenedor.Add (this.bresta);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.contenedor [this.bresta]));
		w4.X = 111;
		w4.Y = 185;
		// Container child contenedor.Gtk.Fixed+FixedChild
		this.bdivision = new global::Gtk.Button ();
		this.bdivision.CanFocus = true;
		this.bdivision.Name = "bdivision";
		this.bdivision.UseUnderline = true;
		this.bdivision.Label = global::Mono.Unix.Catalog.GetString ("DIVIDIR");
		this.contenedor.Add (this.bdivision);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.contenedor [this.bdivision]));
		w5.X = 294;
		w5.Y = 185;
		// Container child contenedor.Gtk.Fixed+FixedChild
		this.bmultiplicar = new global::Gtk.Button ();
		this.bmultiplicar.CanFocus = true;
		this.bmultiplicar.Name = "bmultiplicar";
		this.bmultiplicar.UseUnderline = true;
		this.bmultiplicar.Label = global::Mono.Unix.Catalog.GetString ("MULTIPLICAR");
		this.contenedor.Add (this.bmultiplicar);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.contenedor [this.bmultiplicar]));
		w6.X = 181;
		w6.Y = 184;
		// Container child contenedor.Gtk.Fixed+FixedChild
		this.EntradaNumero1 = new global::Gtk.Entry ();
		this.EntradaNumero1.CanFocus = true;
		this.EntradaNumero1.Name = "EntradaNumero1";
		this.EntradaNumero1.IsEditable = true;
		this.EntradaNumero1.InvisibleChar = '●';
		this.contenedor.Add (this.EntradaNumero1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.contenedor [this.EntradaNumero1]));
		w7.X = 22;
		w7.Y = 71;
		// Container child contenedor.Gtk.Fixed+FixedChild
		this.EntradaNumero2 = new global::Gtk.Entry ();
		this.EntradaNumero2.CanFocus = true;
		this.EntradaNumero2.Name = "EntradaNumero2";
		this.EntradaNumero2.IsEditable = true;
		this.EntradaNumero2.InvisibleChar = '●';
		this.contenedor.Add (this.EntradaNumero2);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.contenedor [this.EntradaNumero2]));
		w8.X = 192;
		w8.Y = 71;
		// Container child contenedor.Gtk.Fixed+FixedChild
		this.Resultado = new global::Gtk.Entry ();
		this.Resultado.CanFocus = true;
		this.Resultado.Name = "Resultado";
		this.Resultado.IsEditable = true;
		this.Resultado.InvisibleChar = '●';
		this.contenedor.Add (this.Resultado);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.contenedor [this.Resultado]));
		w9.X = 155;
		w9.Y = 123;
		// Container child contenedor.Gtk.Fixed+FixedChild
		this.lresultado = new global::Gtk.Label ();
		this.lresultado.Name = "lresultado";
		this.lresultado.LabelProp = global::Mono.Unix.Catalog.GetString ("RESULTADO");
		this.contenedor.Add (this.lresultado);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.contenedor [this.lresultado]));
		w10.X = 57;
		w10.Y = 131;
		this.Add (this.contenedor);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.bsuma.Clicked += new global::System.EventHandler (this.OnBsumaClicked);
		this.bresta.Clicked += new global::System.EventHandler (this.OnBrestaClicked);
		this.bdivision.Clicked += new global::System.EventHandler (this.OnBdivisionClicked);
		this.bmultiplicar.Clicked += new global::System.EventHandler (this.OnBmultiplicarClicked);
	}
}
